name: Deploy to App Engine GCP

on:
  push:
    branches:
      - master
jobs:
  deploy-to-app-engine:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: setup env
      run: |
        echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
        echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash
      
    - name: Checkout
      uses: actions/checkout@v2

          
    #Install Dependencies
    - name: Install Dependencies
      run: |
        go get -d ./...
        
        
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '285.0.0'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}
        export_default_credentials: true 
      
    # Deploy the Docker image to the App Engine
    - name: Deploy
      run: |
        gcloud app deploy --quiet
